apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs
  template:
    metadata:
      labels:
        app: docs
    spec:
      containers:
        - name: docs
          image: us.gcr.io/theta-cell-315515/docs
          env:
            - name: NATSURL
              value: 'http://nats-srv:4222'
            - name: NATSCLUSTERID
              value: 'edocsignature'
            - name: NATSCLIENTID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGOURI
              value: 'mongodb://docs-mongo-srv:27017/docs'
            - name: JWTKEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWTKEY
---
apiVersion: v1
kind: Service
metadata:
  name: docs-srv
spec:
  selector:
    app: docs
  ports:
    - name: docs
      protocol: TCP
      port: 3000
      targetPort: 3000
